### ISSUE TITLE
Shortcode URL does not show up on Firefox.

### ISSUE THREAD

**Issue by LucasMess** [illinois/queue#100]
Seen:
![image](https://user-images.githubusercontent.com/10092027/38757492-e257b460-3f32-11e8-91c4-3e8d391290dc.png)

Expected (Chrome):
![image](https://user-images.githubusercontent.com/10092027/38757557-1397fe04-3f33-11e8-9903-05e88edf78a6.png)

**Comment by nwalters512** [comment]
Oops, I was using an experimental API: https://developer.mozilla.org/en-US/docs/Web/API/Document/origin

This can be fixed by replacing `document.origin` with `document.defaultView.location.origin`.

**Comment by nwalters512** [comment]
Also, happy 100th issue 🎉
