### ISSUE TITLE
fixed location queue notification lists empty location

### ISSUE THREAD

**Issue by trombonekenny** [illinois/queue#110]
I created a fixed location queue and enabled notifications (Win10, Chrome). When something was added to the queue, I got a notification but it had a blank Location: field.

Shouldn't that have the fixed queue mentioned, or perhaps drop the Location: mention at all?

**Comment by nwalters512** [comment]
I would say omit the location, since course staff controls + knows the location? Does that make sense?

**Comment by trombonekenny** [comment]
Or leave it in for consistency in the notifications, but at least fill it in with the right data. I'm okay with either fix.

**Comment by redsn0w422** [comment]
I'm working on this - I think having the location filled in even if it's fixed-location makes more sense.
