### ISSUE TITLE
Allow a course queue to be created as a "confidential queue"

### ISSUE THREAD

**Issue by wadefagen** [illinois/queue#112]
In a "confidential queue" the student name and the topic is visible only to course staff.  Non-course staff would see a default "Another Student" for every entry except their own entry instead of the name/topic.

**Comment by CodeBrew28** [comment]
Self-assigning

**Comment by jackieo5023** [comment]
Self-assigning with @CodeBrew28

**Comment by nwalters512** [comment]
Going to outline some thoughts about this. @CodeBrew28 and @jackieo5023 have been working on some of the frontend for this, which is looking great! However, it's currently only really an illusion of confidentiality: all clients get the same set of questions in the API response, and the websocket gets all of the same data regardless of if a user should see names or not. As this could someday be used in a counseling environment where true confidentiality actually matters, we'll need to make some changes to the backend and data transport to provide that.

# API

This one should be relatively straightforward. When fetching questions for a queue, we can simply check if the authorized user is an admin or on staff and filter out fields based on that. It'll add a little bit of repetition to that endpoint, but I think that's acceptable.

# Websockets

This one is a bit trickier. Right now, all clients subscribe to the same "stream" of data, which is great for simplicity. However, this of course breaks down once we want true confidentiality. For confidential queues, we should add a `queue-[queueID]-staff` variant that includes full name information, and leave the default `queue-[queueID]` websocket with just non-identifying information like timestamps. This websocket will need to be authed, which is a bit annoying but definitely doable (I did a version of this with PrairieLearn for realtime grading results).

# Toggling queue confidentiality

I'm inclined to say that confidentiality can only be set during queue creation and cannot change thereafter. This helps prevent unwanted leaking of personal info if someone on staff accidentally toggles to non-confidential. This also simplified our technical design, as we don't have to account for live switching of student clients between not having name data and then having it.
