### ISSUE TITLE
Admins should be able to join a queue as staff

### ISSUE THREAD

**Issue by nwalters512** [illinois/queue#116]
Going along with the theme of "admins can do anything", they should be able to join as staff. This will make local dev slightly easier since you won't have to add yourself to the course staff list to do anything.

**Comment by warut-vijit** [comment]
Self-assigning

**Comment by nwalters512** [comment]
@warut-vijit status check, are you still working on this or can I put it back into the pool of things people can work on?

**Comment by genevievehelsel** [comment]
I'm gonna pick this up (@warut-vijit let me know otherwise :) )
