### ISSUE TITLE
Add ability to edit existing queues

### ISSUE THREAD

**Issue by genevievehelsel** [illinois/queue#12]
Useful if location changes, for example. Allows us to update queue information without wiping all existing questions.

**Comment by zwang180** [comment]
Want to make sure I understand the issue correctly, I assume this refers to edit queue's title and/or locations right?

**Comment by nwalters512** [comment]
Yep - similar to how we can edit questions. Much of the code will probably be similar!

**Comment by zwang180** [comment]
I see, thx!
