### ISSUE TITLE
Proposal: Add npm fix-lint

### ISSUE THREAD

**Issue by redsn0w422** [illinois/queue#125]
I think it'd be nice if there was an additional script called `fix-lint` or something that called `eslint --ext js . --fix` instead of just `eslint --ext js .`. I **don't** think `lint-js` should be replaced, since obviously not all linter errors can be fixed, and we don't want CI to be changing code.

Thoughts?

**Comment by nwalters512** [comment]
Yeah, this would be good to have! Feel free to PR it.
