### ISSUE TITLE
delete all questions in queue

### ISSUE THREAD

**Issue by genevievehelsel** [illinois/queue#129]
extension of #62 , gives course staff ability to clear the question list

**Comment by PradyumnaShome** [comment]
Sorry I meant this one @nwalters512. Was this part of #62's fix?

**Comment by nwalters512** [comment]
Nope, this hasn't been done yet

**Comment by PradyumnaShome** [comment]
I'm sure what persistence layer is being used, but would this simply be an atomic remove all?

**Comment by nwalters512** [comment]
@PradyumnaShome status check, have you been able to work on this or are you still planning to?

**Comment by nwalters512** [comment]
Sounds good!

**Comment by PiotrGalusza** [comment]
Do we want the 'clear all' option to only appear when the queue is closed, or does it not matter?

**Comment by nwalters512** [comment]
Yeah, I would say only make it apply while it's closed, and wrap it in a bunch of safety and warnings and such.
