### ISSUE TITLE
Show question count for each queue

### ISSUE THREAD

**Issue by genevievehelsel** [illinois/queue#13]
We can use our fancy new websocket infrastructure to make this update in real time, because why not?

**Comment by genevievehelsel** [comment]
@nwalters512 was this resolved with the new homepage, or is this question count meant to be for the actual queue page?

**Comment by nwalters512** [comment]
@genevievehelsel I think this should have been closed with another commit in the previous repo - it's not live updating, but it shows counts, which is what matters :tada:
