### ISSUE TITLE
Rework "cancel question" modal

### ISSUE THREAD

**Issue by nwalters512** [illinois/queue#140]
Simeng told me that the phrasing and coloring on the "cancel question" model is pretty confusing, and I agree. There are two buttons, "Cancel question" and "Cancel", and "Cancel question" is the danger red color. It's also not immediately clear what it even means to cancel a question.

**Comment by Xiangmingchen** [comment]
I will change the "Cancel question" to "Stop answering", is this good enough?

**Comment by nwalters512** [comment]
It'd be helpful to have some more explanatory text in the modal too. We should also think more about phrasing here - making it clear in the modal that if you stop answering a question, the person won't be removed from the queue and will maintain their current place.

**Comment by Xiangmingchen** [comment]
How about changing the message to "You will stop answering this question and this question will stay in the queue."

**Comment by nwalters512** [comment]
Sounds good!
