### ISSUE TITLE
Migration of primary queue endpoint at queue.illinois.edu

### ISSUE THREAD

**Issue by wadefagen** [illinois/queue#166]
Tracks the migration to queue.illinois.edu

**Comment by trombonekenny** [comment]
OK, I've migrated the apache config I tested on edu-staging.cs.illinois.edu over into edu.cs.illinois.edu. That adds in `/etc/httpd/conf.d/vhost-queue.illinois.edu.conf` and `/etc/httpd/conf.d/vhost-edu.cs.illinois.edu.conf` and breaks their respective parts out of `shib.conf` and `ssl.conf`.

On the edu.cs.illinois.edu everything should still work with these additions:
- Fixed the Shibboleth looping around http/https redirection
- Enabled websocket proxying so it's not always polling

On queue.illinois.edu
- the document root is at `/var/www/html/queue`
- https://queue.illinois.edu/q redirects to the queue app (same install as edu.cd/queue/)

Still to do:
- [ ] Put real content (static site?) up at queue.illinois.edu
- [ ] Reconfigure the queue app to listen at /q (note no trailing slash, that's a change but I think it's already been incorporated into the app)
- [ ] Decide how to handle redirects from the old queue URLs. Either in app at the /queue endpoints or we can list them in `vhost-edu.cs.illinois.edu` once the app is active at the queue/q URL

**Comment by nwalters512** [comment]
My plan is to work on a public-facing homepage for `/` over winter break. I think we should save the other route changes until then as well so we have plenty of downtime to coordinate things.

**Comment by wadefagen** [comment]
The same queue is now live at both endpoints: https://edu.cs.illinois.edu/queue/ and https://queue.illinois.edu/q/

We can begin to transition new uses to the queue.illinois.edu endpoint while we work on the static site and redirect scheme.

**Comment by wadefagen** [comment]
The https://edu.cs.illinois.edu/queue/ endpoint is now removed, replaced with a mod_rewrite rule that rewrites all URLs to the https://queue.illinois.edu/q/ URL.

A temp HTML page is also now at https://queue.illinois.edu/ that directs people to the queue or the webform to create a new queue.
