### ISSUE TITLE
Collapse the public message

### ISSUE THREAD

**Issue by aigagror** [illinois/queue#172]
For example the 225 public message on the queue is quite long and it’s kind of annoying to repeatedly scroll down to see who’s on the queue

**Comment by aigagror** [comment]
To clarify, this ability to collapse and expand the message should just be on the instructors POV

**Comment by PiotrGalusza** [comment]
Just to make sure, is this referring to the "Show Staff Message" toggle button? Want to make sure this is actually implemented before it gets marked as completed.

**Comment by PiotrGalusza** [comment]
Ah, missed the 'instructors POV' bit. I understand now.
