### ISSUE TITLE
Remember user's landing URL during login

### ISSUE THREAD

**Issue by wadefagen** [illinois/queue#188]
1. Log out of the queue
2. Visit https://queue.illinois.edu/q/cs225/ (deep links used on course pages, advising offices, etc)
3. Log in
4. You will find yourself at https://queue.illinois.edu/q/  (not cs225) 

Given the use-case for advising offices and new users, dumping them into the main queue page their first time visiting the queue can be a **very** confusing experience.

**Comment by nwalters512** [comment]
I think the cleanest option for this is a query param on the shib login URL, something like `queue.illinois.edu/q/login/shib?redirect=/queue/12345` - Shib will make sure that we get that param after the user authenticates, and we can then do a redirect.
