### ISSUE TITLE
On Duty Staff - Notifications for non-active queues

### ISSUE THREAD

**Issue by HunterADyer** [illinois/queue#203]
I was logged in as an active duty staff on the CARE walk-in tutoring with notifications on, and while my tab was open to CS 225 (course in which I have never been assigned as course staff), I received notifications whenever a student added themselves to the 225 queue, but not the CARE queue.

**Comment by nwalters512** [comment]
Good catch! This is definitely a problem - this stems from the fact that the `activeStaff` dict in the Redux state isn't cleared when navigating between pages, and we only check that the current user is in *any* of the active staff. We should check that for a given person in `activeStaff`, that the queue corresponds to a course that the user is actually staff for.
