### ISSUE TITLE
Error/prompt to enter mandatory fields

### ISSUE THREAD

**Issue by ssethia2** [illinois/queue#217]
Currently, not filling out the topic and/or location fields and trying to add oneself to the queue with the add button does not do anything. An error message or prompt or something else that makes it evident that these fields are required to add one to the queue should be displayed.

**Comment by nwalters512** [comment]
This is being worked on in #195 - thanks for the reminder I still need to get that merged!

**Comment by nwalters512** [comment]
Resolved by #195, this will go out with the next deploy.
