### ISSUE TITLE
Add course-specific pretty URL

### ISSUE THREAD

**Issue by wadefagen** [illinois/queue#22]
Ex:
http://edu.cs.illinois.edu/queue/cs225/ shows only cs225 queues
http://edu.cs.illinois.edu/queue/cs241/ shows only cs241 queues
http://edu.cs.illinois.edu/queue/stat400/ shows only stat400 queues

**Comment by nwalters512** [comment]
If we make some assumptions, this becomes really easy. I'll assume that these will only ever be linked to externally - that is, the request will go to the server and not to the client-side router. Then we can just handle these routes with Express on the server and do a redirect to the right place. We can be particularly clever - if only one active queue exists for a course, we can direct the user straight there without showing them the course page first. Not sure if this is too ✨ magic ✨

**Comment by shreyas208** [comment]
I like the sound of that (auto-redirect if single active queue). One kinda-but-not-exactly related concern is if someone lands on an active queue and then bookmarks that URL, which would no longer be relevant once that queue is gone.

**Comment by nwalters512** [comment]
I could set up requests for inactive queues to go back to the course page. I think chara right now just 404s in that case, but we could do something a bit smarter.

**Comment by nwalters512** [comment]
On second thought, maybe just have a "This queue is no longer available" page, and offer to link them back to the course page?

**Comment by shreyas208** [comment]
I like the latter. Sort of "conditions" users to think of queues as being within courses.
