### ISSUE TITLE
Active course staff and queue message cards acquire inconsistently rendered background on mobile

### ISSUE THREAD

**Issue by PradyumnaShome** [illinois/queue#235]
Steps to reproduce:

On a mobile device, do the following.
1. Go to a queue you are staff in
2. Join the queue
3. You will see a blue and white background on the active staff card, that moves around a bit. Part of this is visible in the card below that, which is the queue staff message card.

This persists even when you leave the active course staff, but is fixed if you reload the page.

Screenshot
![Screenshot_2019-03-15-19-28-36-205_com android chrome](https://user-images.githubusercontent.com/13492296/54495576-d10a4300-48b2-11e9-848a-e40a3e690efb.png)

![Screenshot_2019-03-15-15-59-41-392_com android chrome](https://user-images.githubusercontent.com/13492296/54495599-fbf49700-48b2-11e9-9239-3eebd3ac11fb.png)

**Comment by nwalters512** [comment]
I can't reproduce on Chrome 73. Which browser/version are you using? Can you reproduce this on another device/browser? This seems more like a browser rendering bug than anything.

**Comment by PradyumnaShome** [comment]
Chrome 74.0.3683.75
Cannot reproduce on two other browsers (Opera Touch and Firefox).
