### ISSUE TITLE
Course staff page no longer shows staff name [regression]

### ISSUE THREAD

**Issue by wadefagen** [illinois/queue#238]
In previous versions, the course staff reported the name of each user on staff to other staff members.  In the latest release, only the NetID shows up:

![image](https://user-images.githubusercontent.com/7505610/54938012-8ceef200-4ef3-11e9-801b-471ff155001e.png)

Interestingly, it does show the name correctly if you add the user (but then reverts to only the NetID after a re-render):

![image](https://user-images.githubusercontent.com/7505610/54938081-b3ad2880-4ef3-11e9-8bd8-d7b5c3f6037c.png)

**Comment by nwalters512** [comment]
This was introduced in #233 when we updated Sequelize to v5.1.0. Relevant issue: https://github.com/sequelize/sequelize/issues/10552
