### ISSUE TITLE
Ability to disable student ratings

### ISSUE THREAD

**Issue by daviddalpiaz** [illinois/queue#289]
Would it be possible to disable the need to "grade" students on their preparedness?

I understand that some might want to use this feature, but I would very much hate for students to know that they are being graded during office hours. (It's hard enough to convince them to use office hours, I don't want to make it seem uninviting in any way.) If this is a necessary step, I'd note there should be some messaging to instructors that students do **not** see this information. (At least I hope that's the case, but that's what I found in testing.)

As an aside, currently, if you click one of the buttons, there is no indication that you have clicked one. (Annoying, as I'm trying to get through this menu as quickly as possible and it **requires** that I click one.)

**Comment by rittikaadhikari** [comment]
Resolved by #293
