### ISSUE TITLE
show queue and course name on queue page

### ISSUE THREAD

**Issue by genevievehelsel** [illinois/queue#31]
may be important to give some indication of which queue and course the user is on, esp now that it could be a bit easier to accidentally join the wrong queue from the homepage

**Comment by genevievehelsel** [comment]
could be solved with #3

**Comment by sgorse** [comment]
<img width="1510" alt="screen shot 2018-03-13 at 9 45 36 pm" src="https://user-images.githubusercontent.com/25257442/37380919-b6d8336a-2708-11e8-8070-cbc06508e4e8.png">
I was unsure of where the course name needed to be added. Would it need to be added to this page?

**Comment by genevievehelsel** [comment]
yup! that page

**Comment by sgorse** [comment]
Cool, have you already started working on this part, or is it ok if I start working on this issue?

**Comment by genevievehelsel** [comment]
nope not yet, its all yours :)

**Comment by nwalters512** [comment]
Partially resolved with #81, still have to add the course name though.
