### ISSUE TITLE
Pick a license

### ISSUE THREAD

**Issue by nwalters512** [illinois/queue#43]
I'm fine with something as permissive as possible, don't know if people have any particular thoughts about licensing.

**Comment by wadefagen** [comment]
https://tldrlegal.com/license/university-of-illinois---ncsa-open-source-license-(ncsa)#summary ?

**Comment by wadefagen** [comment]
Classic (default) option: https://opensource.org/licenses/MIT

**Comment by nicholascw** [comment]
btw, seems this can be closed since NCSA License was added.

**Comment by nwalters512** [comment]
Yep; we have a license now!
