### ISSUE TITLE
Prevent CA's from "Start Answering" multiple students

### ISSUE THREAD

**Issue by Muakasan** [illinois/queue#48]

**Comment by wadefagen** [comment]
At some point, there was a suggestion that being able to put a student on "pause" would be desirable while they work on something and you can talk to the next person.

While the "Start Answering" of two students is different than chara, I don't know if this "feature" isn't something that could be a good thing?  I'm rarely a user of the queue, so I want to just make sure this suggestion is out there -- not to sway the conversation one way or another.

**Comment by nwalters512** [comment]
I've never really used the queue like that, not sure about other people in the course. I think the way that would be done right now is to just cancel the "answering" status and leave the person on the queue to revisit them later.

If we want actual support for leaving students in a paused state while assigned to a specific CA, that would be another issue and should probably be handled separately from this.
