### ISSUE TITLE
Allow Illinois courses to use this as a service

### ISSUE THREAD

**Issue by wadefagen** [illinois/queue#49]
- Created a process for Illinois courses to be added to the queue (this may be just a dumb web form that e-mails someone)
- Advertise that process in the README

(This is a subset of the work that is likely done under #19)

**Comment by nwalters512** [comment]
@wadefagen is this any different from #23?

**Comment by wadefagen** [comment]
Oops -- I read @genevievehelsel #19 and was like "yes, this is great, I should make sure to write this SaaS thing down", but I already did.

Thanks!
