### ISSUE TITLE
Hide new question form for on duty staff

### ISSUE THREAD

**Issue by genevievehelsel** [illinois/queue#57]
Dont think on duty staff needs to add a question to the queue. only reason I would see that being the case is if the staff wants to put a dummy question on the queue to mark the end of the queue.

in that case, maybe a button that would allow the queue to be closed for new questions, but allows the current questions to be viewed and answered? 

Not sure if the button would encourage courses to just use one queue for eternity (instead of deleting and making new queues). Not sure if this would like to be avoided or not.

**Comment by nwalters512** [comment]
This kind of touches on my broader question of if we even Hain anything by making a new queue every day - I don't really see why that's necessary. @

**Comment by genevievehelsel** [comment]
yeah I agree, the only point I see right now is so we can avoid people adding themselves to the queue well before office hours start / well after office hours end. but some type of staff button that would disable students adding themselves to the queue would help this issue.

**Comment by nwalters512** [comment]
Yeah, a single queue would have to go hand-in-hand with some kind of concept of a queue being open or closed. This seems to be the model that advising is using; we could add specific support for that kind of queue, or just make it the default. That would definitely require some coordinating to make sure people understand the new model, though.
