### ISSUE TITLE
Allow course staff to add people to the queue

### ISSUE THREAD

**Issue by wadefagen** [illinois/queue#65]
Candy (in CS Advising) e-mailed me about a problem they had yesterday where 3 people were unable to log into the queue (probably due to the shib auth error).  Even as an admin, she could only add one of them to the queue herself.

A worthwhile feature would be to allow admins ("course staff") to add a question to the queue "as someone else" (eg: an ask a question with a NetID field?).

**Comment by nwalters512** [comment]
This seems like a horrible, horrible hack for something that shouldn't ever be needed. The right thing to do is get to the bottom of the Shib issue, not work around it being broken.

**Comment by wadefagen** [comment]
I agree that in the current CS 225 usage, it doesn't make sense.  I disagree that it is a horrible hack.

There are models where this method is use right now.  For example, the intro CHEM courses have a similar queuing system that they use in the Chemistry Learning Center (https://chemistry.illinois.edu/clc).  They have students swipe in to register for their queue and then are placed on a queue or assigned someone to help them out.  The student is added to the queue, but cannot add themselves.

At some point in the past (not sure how it is this semester), this was also how CS 125's queue also worked.  They wanted to verify the person was physically there before they were enqeueud.  This may be a model we don't care to support, but is a widely used model.

**Comment by nwalters512** [comment]
Gotcha, that was the context I needed. The way you framed it in the original issue made me think you wanted this solely to work around the fact that Shib is misbehaving :)

**Comment by nwalters512** [comment]
So yes, this is definitely a model we should support.

**Comment by trombonekenny** [comment]
And it's Holly, so we definitely want to make sure she's happy. :)
